version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: trustmesh_postgres_staging
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: trustmesh_staging
    ports:
      - "5432:5432"
    volumes:
      - pgdata_staging:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_staging:
