"""Add user_id and org_id to negotiation_sessions

Revision ID: 677b6e36ce2e
Revises: 884c4121965c
Create Date: 2026-07-18 10:33:41.004123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677b6e36ce2e'
down_revision: Union[str, Sequence[str], None] = '884c4121965c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negotiation_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('org_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_negotiation_sessions_org_id', 'organizations', ['org_id'], ['id'])
        batch_op.create_foreign_key('fk_negotiation_sessions_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negotiation_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_negotiation_sessions_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_negotiation_sessions_org_id', type_='foreignkey')
        batch_op.drop_column('org_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
